### PR TITLE
Update organisers.yaml

### PR DESCRIPTION
**Pull request by mcne65**
name: Sirani McNeill
+      twitter: mcne65
+      description: Junior software developer and cybersecurity expert. Diversity and Inclusion lead for CampJS. 
+      Happy to organise crafting workshops 
+      email: siranimcneill020@gmail.com 
+      image: https://twitter.com/mcne65

### CODE REVIEW

**Comment by AshKyd** [comment]
Hm, can you add your own image/photo to the `images/profiles` folder? It's currently using Adam Brady's.

**Comment by mcne65** [comment]
Depends, if you are going to give me write access for that repository profile so that I upload my photo. Otherwise, here is my photo for you to put up but was planning to do this myself.
img_0730

**Comment by AshKyd** [comment]
You can submit this all as part of the pull request. Do you need a hand to go through it?

**Comment by mcne65** [comment]
name: Sirani McNeill

 twitter: mcne65
 description: Junior software developer and cybersecurity expert. Diversity and Inclusion lead for CampJS. 
 Happy to organise crafting workshops 
 email: siranimcneill020@gmail.com 
 image: https://twitter.com/mcne65

Please put this through CampJS website as I need a hand for this

**Comment by AshKyd** [comment]
Closing this one in favour of #71

**Pull request closed without merging**
